tcg: move free_tcg_plugin_context to the correct macro range
`free_tcg_plugin_context` is used in `!CONFIG_USER_ONLY`.
Move it to the macro range.

Build werror:

../tcg/tcg.c:767:13: error: ‘free_tcg_plugin_context’ defined but not used [-Werror=unused-function]
  767 | static void free_tcg_plugin_context(TCGContext *s)
      |             ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes: f797e2713(tcg/mttcg: enable threads to unregister in tcg_ctxs[])
Signed-off-by: liuxiangdong <liuxiangdong5@huawei.com>