hw/sdhci: fix -Werror=maybe-uninitialized false-positive cherry-pick from ea34d1dd968956ec418c4278b39b6c44bb606d9c
../hw/sd/sdhci.c:846:16: error: ‘res’ may be used uninitialized [-Werror=maybe-uninitialized]

False-positive, because "length" is non-null.

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
Reviewed-by: Alex Bennée <alex.bennee@linaro.org>

Signed-off-by: guping <guping_yewu@cmss.chinamobile.com>