hw/virtio: fix -Werror=maybe-uninitialized
cherry-pick from 3073c6b99557042476add4ddbcc8c834ae70fce5

hw/virtio: fix -Werror=maybe-uninitialized

../hw/virtio/vhost-shadow-virtqueue.c:545:13: error: ‘r’ may be used uninitialized [-Werror=maybe-uninitialized]

Set `r` to 0 at every loop, since we don't check vhost_svq_get_buf()
return value.

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
Reviewed-by: Stefano Garzarella <sgarzare@redhat.com>

Signed-off-by: guping <guping_yewu@cmss.chinamobile.com>